path = '~/Documents/research/AWS/sparse_filtering/saved/';
addpath(genpath(path))

folders = dir([path, '/2015*']);

for folder = 1:numel(folders)

    fileNames = dir(...
        [...
            path, ...
            folders(folder).name, ...
            '/activation_raw*.mat'...
        ]...
    );

    master = []; 
    for file = 1:numel(fileNames)
        temp = load(...
            [
                path,...
                folders(folder).name,...
                '/'...
                fileNames(file).name...
            ]...
        );
        field = fieldnames(temp); 
        temp = reshape(...
            temp.(field{1}), [...
                size(temp.(field{1}), 1),...
                size(temp.(field{1}), 2),...
                size(temp.(field{1}), 3) * size(temp.(field{1}), 4)...
            ]...
        );
        master = [master; temp];
        disp(num2str(file))
    end

    save(...
        [...
            path, ...
            folders(folder).name, ...
            '/concatenated_activations.mat'...
        ],...
    'master'...
    )...
    
end