path = '~/Documents/research/AWS/sparse_filtering/saved/';
addpath(genpath(path))

folders = dir([path, '/2015*']);

% select only most recent folder for concatentation (optional)
folders = folders(end);  % end

% automatically get batch size and activation output size from helper
helper_file = [path, folders.name, '/helper.mat']; 
load(helper_file)
master = zeros(batches * output_size(1), output_size(2), output_size(3));
% master = zeros(50000, 5000, 16);
batch_size = output_size(1);

for folder = 1:numel(folders)

    fileNames = dir(...
        [...
            path, ...
            folders(folder).name, ...
            '/activations_norm*.mat'...  % raw
        ]...
    );

    master = []; 
    batch = 1; 
    for file = 1:numel(fileNames)
        temp = load(...
            [
                path,...
                folders(folder).name,...
                '/'...
                fileNames(file).name...
            ]...
        );
        field = fieldnames(temp); 
        temp = reshape(...
            temp.(field{1}), [...
                size(temp.(field{1}), 1),...
                size(temp.(field{1}), 2),...
                size(temp.(field{1}), 3) * size(temp.(field{1}), 4)...
            ]...
        );
        batch_begin = (batch - 1) * batch_size + 1;
        batch_end = batch_begin + batch_size - 1;
        master(batch_begin:batch_end, :, :) = temp;
        disp(num2str(file))
        batch = batch + 1;
    end

    save(...
        [...
            path, ...
            folders(folder).name, ...
            '/concatenated_activations.mat'...
        ],...
    'master',...
    '-v7.3'...
    )...
    
end